"""
WeatherAPI.com API docs
https://www.weatherapi.com/docs/
"""

WEATHERAPI_UNITS = {
    "metric": "Metric",
    "imperial": "Imperial",
}

WEATHERAPI_LANGUAGES = {
    "ar": "Arabic",
    "bn": "Bengali",
    "bg": "Bulgarian",
    "zh": "Chinese Simplified",
    "zh_tw": "Chinese Traditional",
    "cs": "Czech",
    "da": "Danish",
    "en": "English",  # "en" is not supported. Must remove to get the default lanague that is english, otherwise get another weird language arabic.
    "nl": "Dutch",
    "fi": "Finnish",
    "fr": "French",
    "de": "German",
    "el": "Greek",
    "hi": "Hindi",
    "hu": "Hungarian",
    "it": "Italian",
    "ja": "Japanese",
    "jv": "Javanese",
    "ko": "Korean",
    "zh_cmn": "Mandarin",
    "mr": "Marathi",
    "pl": "Polish",
    "pt": "Portuguese",
    "pa": "Punjabi",
    "ro": "Romanian",
    "ru": "Russian",
    "sr": "Serbian",
    "si": "Sinhalese",
    "sk": "Slovak",
    "es": "Spanish",
    "sv": "Swedish",
    "ta": "Tamil",
    "te": "Telugu",
    "tr": "Turkish",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "vi": "Vietnamese",
    "zh_wuu": "Wu (Shanghainese)",
    "zh_hsn": "Xiang",
    "zh_yue": "Yue (Cantonese)",
    "zu": "Zulu",
}
# WEATHERAPI_LANGUAGES = {
#     "ar": "العربية",
#     "bn": "বাংলা",
#     "bg": "Български",
#     "zh": "简体中文",
#     "zh_tw": "繁體中文",
#     "cs": "Čeština",
#     "da": "Dansk",
#     "nl": "Nederlands",
#     "fi": "Suomi",
#     "fr": "Français",
#     "de": "Deutsch",
#     "el": "Ελληνικά",
#     "hi": "हिन्दी",
#     "hu": "Magyar",
#     "it": "Italiano",
#     "ja": "日本語",
#     "jv": "Basa Jawa",
#     "ko": "한국어",
#     "zh_cmn": "普通话",
#     "mr": "मराठी",
#     "pl": "Polski",
#     "pt": "Português",
#     "pa": "ਪੰਜਾਬੀ",
#     "ro": "Română",
#     "ru": "Русский",
#     "sr": "Српски",
#     "si": "සිංහල",
#     "sk": "Slovenčina",
#     "es": "Español",
#     "sv": "Svenska",
#     "ta": "தமிழ்",
#     "te": "తెలుగు",
#     "tr": "Türkçe",
#     "uk": "Українська",
#     "ur": "اردو",
#     "vi": "Tiếng Việt",
#     "zh_wuu": "吴语",
#     "zh_hsn": "湘语",
#     "zh_yue": "粤语",
#     "zu": "isiZulu"
# }
